"""Finance building blocks: returns, metrics, fixed income, derivatives, portfolios."""

from __future__ import annotations

from .derivatives import (
    binomial_american_option,
    binomial_european_option,
    binomial_greeks,
    call_payoff,
    forward_payoff,
    long_straddle_payoff,
    put_call_parity_gap,
    put_payoff,
)
from .fixed_income import (
    bond_convexity,
    bond_price,
    discount_curve,
    discount_factor,
    macaulay_duration,
    modified_duration,
    present_value,
    yield_to_maturity,
    zero_coupon_bond_price,
)
from .metrics import (
    PERIODS_PER_YEAR,
    annualized_mean,
    annualized_volatility,
    calmar_ratio,
    correlation_matrix,
    covariance_matrix,
    deflated_sharpe_ratio,
    expected_max_sharpe,
    max_drawdown,
    periods_per_year,
    probabilistic_sharpe_ratio,
    sharpe_ratio,
    sortino_ratio,
    turnover,
)
from .portfolio import (
    buy_and_hold_weights,
    equal_weights,
    ledoit_wolf_covariance,
    minimum_variance_portfolio,
    portfolio_return,
    portfolio_variance,
    shrinkage_covariance,
)
from .returns import (
    cumulative_returns,
    log_returns,
    log_to_simple,
    simple_returns,
    simple_to_log,
    total_return,
)

__all__ = [
    "binomial_american_option",
    "binomial_greeks",
    "bond_convexity",
    "calmar_ratio",
    "deflated_sharpe_ratio",
    "expected_max_sharpe",
    "ledoit_wolf_covariance",
    "macaulay_duration",
    "modified_duration",
    "probabilistic_sharpe_ratio",
    "sortino_ratio",
    "PERIODS_PER_YEAR",
    "annualized_mean",
    "annualized_volatility",
    "binomial_european_option",
    "bond_price",
    "buy_and_hold_weights",
    "call_payoff",
    "correlation_matrix",
    "covariance_matrix",
    "cumulative_returns",
    "discount_curve",
    "discount_factor",
    "equal_weights",
    "forward_payoff",
    "log_returns",
    "log_to_simple",
    "long_straddle_payoff",
    "max_drawdown",
    "minimum_variance_portfolio",
    "periods_per_year",
    "portfolio_return",
    "portfolio_variance",
    "present_value",
    "put_call_parity_gap",
    "put_payoff",
    "sharpe_ratio",
    "shrinkage_covariance",
    "simple_returns",
    "simple_to_log",
    "total_return",
    "turnover",
    "yield_to_maturity",
    "zero_coupon_bond_price",
]
