"""Loaders for repository-owned sample data.

Only repository-owned synthetic data is loaded here. Third-party market data is
never bundled; see ``scripts/optional_download_market_data.py`` and
``data/README.md`` for the optional, user-driven download workflow.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from .validation import validate_price_frame


def _repo_root() -> Path:
    """Return the repository root directory.

    The package lives at ``<root>/src/quant_math_roadmap``; the root is three
    parents up from this file.
    """
    return Path(__file__).resolve().parents[3]


def sample_data_dir() -> Path:
    """Return the path to the bundled sample-data directory."""
    return _repo_root() / "data" / "sample"


def load_prices_csv(path: str | Path, *, validate: bool = True) -> pd.DataFrame:
    """Load a price panel from a CSV file with a leading date column.

    Args:
        path: Path to a CSV file whose first column is a parseable date.
        validate: When ``True``, run :func:`validate_price_frame` and raise on
            failure.

    Returns:
        A price ``DataFrame`` indexed by date.
    """
    prices = pd.read_csv(path, index_col=0, parse_dates=True)
    prices.index.name = prices.index.name or "date"
    prices = prices.sort_index()
    if validate:
        validate_price_frame(prices).raise_if_failed()
    return prices


def load_sample_prices(*, validate: bool = True) -> pd.DataFrame:
    """Load the bundled synthetic price panel (``data/sample/synthetic_prices.csv``).

    The file is generated by ``scripts/generate_synthetic_dataset.py``. If it is
    missing, regenerate it with::

        uv run python scripts/generate_synthetic_dataset.py

    Args:
        validate: When ``True``, validate the loaded frame.

    Returns:
        A price ``DataFrame`` indexed by business day.
    """
    path = sample_data_dir() / "synthetic_prices.csv"
    if not path.exists():
        raise FileNotFoundError(
            f"Sample data not found at {path}. Generate it with:\n"
            "    uv run python scripts/generate_synthetic_dataset.py"
        )
    return load_prices_csv(path, validate=validate)
